apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-UI
spec:
  replicas: 3
  selector:
    matchLabels:
      app: micro-UI
  template:
    metadata:
      labels:
        app: micro-UI
    spec:
      containers:
      - name: micro-UI
        image: azureaksregistry1.azurecr.io/todo-ui:v1
        ports:
        - containerPort: 8000
