apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: micro-ui
  template:
    metadata:
      labels:
        app: micro-ui
    spec:
      containers:
      - name: micro-ui
        image: acrrg1.azurecr.io/todo-ui:v3
        ports:
        - containerPort: 80
