apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
    app.kubernetes.io/name: myingress
spec:
  rules:
  - host: ui.devops-engineer-adda.store
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: micro-ui
            port: 
              number: 80
