apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
    app.kubernetes.io/name: myingress
spec:
  ingressClassName: nginx
  rules:
  - host: newui.devops-engineer-adda.store
    http:
      paths:
      - pathType: Prefix
        path: "/" # todo api root path p sunta h ..devloper can change
        backend:
          service:
            name: micro-ui
            port: 
              number: 80 #service ka port map krte h
